### ISSUE TITLE
Error while executing : pip install ckwrap [ python 3.6 / MacOS Mojave 10.14.6 ]

### ISSUE THREAD

**Issue by barikajit** [djdt/ckwrap#1]
Hi, 

I tried installing ckwrap on MacOS Mojave 10.14.6 . I have python 3.6 installed on my system.
Below is the error log. Could you please help me with this issue?
Thx

$ pip install ckwrap
Collecting ckwrap
  Using cached ckwrap-0.1.7.tar.gz (119 kB)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from ckwrap) (1.16.2)
Requirement already satisfied: Cython in ./anaconda3/lib/python3.6/site-packages (from ckwrap) (0.29.6)
Building wheels for collected packages: ckwrap
  Building wheel for ckwrap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/ajitbarik/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/setup.py'"'"'; __file__='"'"'/private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-wheel-nbynhrn9
       cwd: /private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/ckwrap
  copying ckwrap/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
  copying ckwrap/result.py -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
  copying ckwrap/ckwrap.py -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
  copying ckwrap/_ckwrap.pyx -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
  running build_ext
  building '_ckwrap' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/ckwrap
  creating build/temp.macosx-10.7-x86_64-3.6/Ckmeans.1d.dp
  creating build/temp.macosx-10.7-x86_64-3.6/Ckmeans.1d.dp/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ajitbarik/anaconda3/include -arch x86_64 -I/Users/ajitbarik/anaconda3/include -arch x86_64 -ICkmeans.1d.dp/src -I/Users/ajitbarik/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/ajitbarik/anaconda3/include/python3.6m -c ckwrap/_ckwrap.cpp -o build/temp.macosx-10.7-x86_64-3.6/ckwrap/_ckwrap.o -std=c++11 -g0
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  ckwrap/_ckwrap.cpp:657:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ckwrap
  Running setup.py clean for ckwrap
Failed to build ckwrap
Installing collected packages: ckwrap
    Running setup.py install for ckwrap ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/ajitbarik/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/setup.py'"'"'; __file__='"'"'/private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-record-ezx6ghj4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ajitbarik/anaconda3/include/python3.6m/ckwrap
         cwd: /private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/ckwrap
    copying ckwrap/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
    copying ckwrap/result.py -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
    copying ckwrap/ckwrap.py -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
    copying ckwrap/_ckwrap.pyx -> build/lib.macosx-10.7-x86_64-3.6/ckwrap
    running build_ext
    building '_ckwrap' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/ckwrap
    creating build/temp.macosx-10.7-x86_64-3.6/Ckmeans.1d.dp
    creating build/temp.macosx-10.7-x86_64-3.6/Ckmeans.1d.dp/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ajitbarik/anaconda3/include -arch x86_64 -I/Users/ajitbarik/anaconda3/include -arch x86_64 -ICkmeans.1d.dp/src -I/Users/ajitbarik/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/ajitbarik/anaconda3/include/python3.6m -c ckwrap/_ckwrap.cpp -o build/temp.macosx-10.7-x86_64-3.6/ckwrap/_ckwrap.o -std=c++11 -g0
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    ckwrap/_ckwrap.cpp:657:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/ajitbarik/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/setup.py'"'"'; __file__='"'"'/private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-install-vebi2cb8/ckwrap_d0225c16dc9349bda7252215e6abb37b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/k1/cjly1lr53_vf9wmvf7171k640000gn/T/pip-record-ezx6ghj4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ajitbarik/anaconda3/include/python3.6m/ckwrap Check the logs for full command output.

**Comment by iled** [comment]
I also had some error while installing `ckwrap` **0.1.7**. The previous version installed fine, so I would suggest you try that as a workaround:

    pip install ckwrap==0.1.6

**Comment by djdt** [comment]
I think you need to either upgrade Python to 3.7+ or install c++ build tools for IOS. I can release a new version with 3.6 support added back in if that's better for you.

**Comment by barikajit** [comment]
Hi,

My team already managed to find a fix for this. Thanks for the follow-up.
