### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by cmantas** [djdt/ckwrap#5]
Hello.
This is a nice and useful project.
Are you open to outside contributions/PRs?.

In particular I'm thinking of the following 2
1. Some examples/documentation (on the main Readme or a separate .md file)
2. An OO interface (aka a CKmeans class) with an API that's loosely similar to [scikit's KMeans class](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html). (It's totally understandable if this is outside of the scope of this project)

**Comment by djdt** [comment]
Sorry for the slow reply, I am open to contributions. I think that the interface is a bit outside the scope but some examples on the front page would be nice.
